### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by bendiknesbo** [klaviyo/klaviyo-android-sdk#16]
Please add documentation on how to install, configure, and set up this SDK.

The help-database only lists how to get started on iOS: https://help.klaviyo.com/hc/en-us/sections/360003732352-Push-Notifications

**Comment by jordan-griffin** [comment]
Hi Ben,

Thanks for bringing this to our attention. The Android SDK is still in the early stages of development. There will be documentation added to the Klaviyo help center when we feel we have a stable release ready. At this point we still plan to make breaking changes to the SDK as development continues.

I'll add a README which warns on the current state of the SDK later today and close out this issue when its in place.

**Comment by jordan-griffin** [comment]
README added to let developers know that this project is still in its pre-alpha stages, so I'm going to close out this issue and we'll update with documentation as we approach releases.
