### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by kcjian** [klaviyo/klaviyo-android-sdk#178]
### Checklist

- [X] I have read the [contributing guidelines](https://github.com/klaviyo/klaviyo-android-sdk/blob/master/.github/CONTRIBUTING.md)
- [ ] I have determined whether this bug is also reproducible in a vanilla Android project
- [ ] If possible, I've reproduced the issue using the `master` branch or latest release of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/klaviyo/klaviyo-android-sdk/issues) or [pull request](https://github.com/klaviyo/klaviyo-android-sdk/pulls).

### Description

```markdown
Firebase report error
```

### Expected behavior

```markdown
Firebase do not report this error
```

### Actual behavior

```markdown
Fatal Exception: java.util.ConcurrentModificationException
java.util.ArrayList$Itr.next (ArrayList.java:860)
com.klaviyo.core.networking.KlaviyoNetworkMonitor.broadcastNetworkChange (KlaviyoNetworkMonitor.kt:127)
com.klaviyo.core.networking.KlaviyoNetworkMonitor.access$broadcastNetworkChange (KlaviyoNetworkMonitor.kt:16)
com.klaviyo.core.networking.KlaviyoNetworkMonitor$networkCallback$1.onAvailable (KlaviyoNetworkMonitor.kt:33)
android.net.ConnectivityManager$CallbackHandler.handleMessage (ConnectivityManager.java:2792)
android.os.Handler.dispatchMessage (Handler.java:108)
android.os.Looper.loop (Looper.java:206)
android.os.HandlerThread.run (HandlerThread.java:65)
```

### Steps to reproduce

```markdown
none
```

### The Klaviyo Android SDK version information

2.4.0

### Device Information

 Moto G Stylus 5G Android 14 \Galaxy S8 Android 9......

### Android API Level

android COMPILE_SDK_VERSION 34
android TARGET_SDK_VERSION 33
android MIN_SDK_VERSION 24

**Comment by dan-peluso** [comment]
Thanks for creating this! We've got a fix slated for next release.

**Comment by kuangyliang** [comment]
I also encountered this issue, which is causing a large number of crash reports in Firebase. This is very urgent. When will a new version be released to resolve it?

**Comment by houweiAndroid** [comment]
We are experiencing the same issue in our production project, which has led to a significant number of crashes. When can we expect it to be fixed?

**Comment by evan-masseau** [comment]
thank you all for the feedback, we are prioritizing a patch release to address the issue!

**Comment by dan-peluso** [comment]
https://github.com/klaviyo/klaviyo-android-sdk/releases/tag/2.4.1

Patch release for this issue
